package com.pvp.travelmatch.service;
import com.fasterxml.jackson.databind.*; import com.pvp.travelmatch.dto.*; import com.pvp.travelmatch.entity.*; import com.pvp.travelmatch.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.beans.factory.annotation.Value; import org.springframework.data.domain.*; import org.springframework.http.*; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException; import java.time.*; import java.util.*;
@Service @RequiredArgsConstructor public class MonetizationService{
 private final UserRepository users; private final SubscriptionRepository subscriptions; private final PaymentTransactionRepository payments; private final BoostedTravelPlanRepository boosts; private final ProfileViewRepository views; private final TravelPlanRepository plans; private final AuditLogRepository audits; private final PaymentProviderService provider; private final ObjectMapper mapper;
 @Value("${travelmatch.monetization.premium-price-paise:49900}") long premiumPrice; @Value("${travelmatch.monetization.boost-price-paise:9900}") long boostPrice; @Value("${travelmatch.monetization.premium-days:30}") long premiumDays; @Value("${travelmatch.monetization.boost-duration-hours:24}") long boostHours; @Value("${travelmatch.monetization.boost-multiplier:2.0}") double boostMultiplier; @Value("${travelmatch.monetization.free-request-limit:10}") int freeRequestLimit; @Value("${razorpay.key-id:}") String keyId; @Value("${travelmatch.affiliate.enabled:false}") boolean affiliateEnabled; @Value("${travelmatch.affiliate.flight-url:}") String flightPartnerUrl; @Value("${travelmatch.affiliate.hotel-url:}") String hotelPartnerUrl; @Value("${travelmatch.affiliate.insurance-url:}") String insuranceUrl;
 private User me(){return users.findByEmail(SecurityContextHolder.getContext().getAuthentication().getName()).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"User not found"));}
 public boolean isPremium(User u){return subscriptions.findByUserId(u.getId()).map(s->s.getPlan()==SubscriptionPlan.PREMIUM&&s.getStatus()==SubscriptionStatus.ACTIVE&&s.getEndDate()!=null&&s.getEndDate().isAfter(LocalDateTime.now())).orElse(false);}
 public PremiumStatusResponse status(){User u=me();Subscription s=subscriptions.findByUserId(u.getId()).orElse(null);return new PremiumStatusResponse(isPremium(u),s==null?"FREE":s.getPlan().name(),s==null?"EXPIRED":s.getStatus().name(),premiumPrice,boostPrice,freeRequestLimit,affiliateEnabled,flightPartnerUrl,hotelPartnerUrl,insuranceUrl);}
 @Transactional public PaymentOrderResponse createPremiumOrder(){User u=me();if(isPremium(u))throw new ResponseStatusException(HttpStatus.CONFLICT,"You already have an active Premium subscription");var o=provider.createOrder(premiumPrice,"premium-"+u.getId()+"-"+System.currentTimeMillis(),PaymentType.PREMIUM,null);PaymentTransaction t=PaymentTransaction.builder().user(u).provider(PaymentProvider.RAZORPAY).type(PaymentType.PREMIUM).status(PaymentStatus.CREATED).providerOrderId(o.orderId()).amount(o.amount()).currency(o.currency()).createdAt(LocalDateTime.now()).updatedAt(LocalDateTime.now()).build();payments.save(t);audit(u,"PAYMENT_ORDER_CREATED","PAYMENT",t.getId(),"Premium payment order created");return new PaymentOrderResponse(o.orderId(),o.amount(),o.currency(),keyId,"PREMIUM",null);}
 @Transactional public SubscriptionResponse verifyPremium(PaymentVerificationRequest r){User u=me();PaymentTransaction t=owned(r.getOrderId(),u);if(t.getType()!=PaymentType.PREMIUM)throw bad("Payment is not a Premium order");if(t.getStatus()!=PaymentStatus.SUCCESS){if(!provider.verifyPaymentSignature(r.getOrderId(),r.getPaymentId(),r.getSignature()))throw bad("Invalid payment signature");t.setProviderPaymentId(r.getPaymentId());t.setStatus(PaymentStatus.SUCCESS);payments.save(t);activatePremium(u);}return subscriptionResponse(subscriptions.findByUserId(u.getId()).orElseThrow());}
 @Transactional public SubscriptionResponse cancel(){User u=me();Subscription s=subscriptions.findByUserId(u.getId()).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"No subscription found"));if(!isPremium(u))throw new ResponseStatusException(HttpStatus.CONFLICT,"No active Premium subscription");s.setStatus(SubscriptionStatus.CANCELLED);s.setAutoRenew(false);subscriptions.save(s);audit(u,"SUBSCRIPTION_CANCELLED","SUBSCRIPTION",s.getId(),"Premium subscription cancelled");return subscriptionResponse(s);}
 @Transactional public PaymentOrderResponse createBoostOrder(Long planId){User u=me();TravelPlan p=plans.findById(planId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Travel plan not found"));if(!u.getId().equals(p.getUser().getId()))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"You can only boost your own trip");if(!"ACTIVE".equalsIgnoreCase(p.getStatus()))throw bad("Only active trips can be boosted");if(boosts.findActive(planId,LocalDateTime.now()).isPresent())throw new ResponseStatusException(HttpStatus.CONFLICT,"This trip is already boosted");var o=provider.createOrder(boostPrice,"boost-"+planId+"-"+System.currentTimeMillis(),PaymentType.BOOST,planId);payments.save(PaymentTransaction.builder().user(u).provider(PaymentProvider.RAZORPAY).type(PaymentType.BOOST).status(PaymentStatus.CREATED).providerOrderId(o.orderId()).amount(o.amount()).currency(o.currency()).referenceId(planId).createdAt(LocalDateTime.now()).updatedAt(LocalDateTime.now()).build());return new PaymentOrderResponse(o.orderId(),o.amount(),o.currency(),keyId,"BOOST",planId);}
 @Transactional public BoostResponse verifyBoost(Long planId,PaymentVerificationRequest r){User u=me();TravelPlan p=plans.findById(planId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Travel plan not found"));if(!u.getId().equals(p.getUser().getId()))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"You can only boost your own trip");PaymentTransaction t=owned(r.getOrderId(),u);if(t.getType()!=PaymentType.BOOST||!Objects.equals(t.getReferenceId(),planId))throw bad("Payment does not belong to this boost");if(t.getStatus()!=PaymentStatus.SUCCESS){if(!provider.verifyPaymentSignature(r.getOrderId(),r.getPaymentId(),r.getSignature()))throw bad("Invalid payment signature");t.setProviderPaymentId(r.getPaymentId());t.setStatus(PaymentStatus.SUCCESS);payments.save(t);}var active=boosts.findActive(planId,LocalDateTime.now());if(active.isPresent())return toBoost(active.get());LocalDateTime now=LocalDateTime.now();BoostedTravelPlan b=boosts.save(BoostedTravelPlan.builder().travelPlan(p).user(u).multiplier(boostMultiplier).startedAt(now).expiresAt(now.plusHours(boostHours)).createdAt(now).active(true).build());audit(u,"BOOST_ACTIVATED","TRAVEL_PLAN",planId,"Paid 24-hour feed boost activated");return toBoost(b);}
 @Transactional public void recordProfileView(Long viewedId){User viewer=me();if(viewer.getId().equals(viewedId))return;User target=users.findById(viewedId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Traveler not found"));LocalDateTime since=LocalDateTime.now().minusHours(24);ProfileView v=views.findRecent(viewer.getId(),viewedId,since).orElseGet(()->views.findByViewerIdAndViewedUserId(viewer.getId(),viewedId).orElseGet(()->ProfileView.builder().viewer(viewer).viewedUser(target).build()));v.setViewedAt(LocalDateTime.now());views.save(v);}
 public List<ProfileViewResponse> profileViews(){User u=me();if(!isPremium(u))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Premium subscription required");return views.findByViewedUserIdOrderByViewedAtDesc(u.getId(),PageRequest.of(0,100)).stream().map(v->new ProfileViewResponse(v.getViewer().getId(),v.getViewer().getName(),v.getViewer().getUsername(),photo(v.getViewer()),v.getViewer().getCity(),v.getViewedAt())).toList();}
 public int freeRequestLimit(){return freeRequestLimit;}
 public Page<AdminPaymentResponse> adminPayments(int page,int size){requireAdmin();return payments.findAllByOrderByCreatedAtDesc(PageRequest.of(Math.max(0,page),Math.min(Math.max(size,1),100),Sort.by(Sort.Direction.DESC,"createdAt"))).map(t->new AdminPaymentResponse(t.getId(),t.getUser().getId(),t.getUser().getName(),t.getType().name(),t.getStatus().name(),t.getAmount(),t.getCurrency(),t.getProviderOrderId(),t.getProviderPaymentId(),t.getReferenceId(),t.getCreatedAt()));}
 public Map<String,Object> adminMetrics(){requireAdmin();Map<String,Object>m=new LinkedHashMap<>();m.put("premiumUsers",subscriptions.countByPlan(SubscriptionPlan.PREMIUM));m.put("activeSubscriptions",subscriptions.countByStatusAndEndDateAfter(SubscriptionStatus.ACTIVE,LocalDateTime.now()));m.put("cancelledSubscriptions",subscriptions.countByStatus(SubscriptionStatus.CANCELLED));m.put("expiredSubscriptions",subscriptions.countByStatus(SubscriptionStatus.EXPIRED));m.put("totalPayments",payments.count());m.put("successfulPayments",payments.countByStatus(PaymentStatus.SUCCESS));m.put("failedPayments",payments.countByStatus(PaymentStatus.FAILED));m.put("totalBoosts",boosts.count());m.put("activeBoosts",boosts.countByActiveTrue());m.put("revenuePaise",payments.sumSuccessfulAmount());return m;}
 @Transactional public void webhook(String payload,String signature){if(!provider.verifyWebhookSignature(payload,signature))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid webhook signature");try{JsonNode r=mapper.readTree(payload),e=r.path("event");String event=e.asText(),order=r.path("payload").path("payment").path("entity").path("order_id").asText(null),payment=r.path("payload").path("payment").path("entity").path("id").asText(null);if(order==null)return;PaymentTransaction t=payments.findByProviderOrderId(order).orElse(null);if(t==null||t.getStatus()==PaymentStatus.SUCCESS)return;if("payment.captured".equals(event)){t.setStatus(PaymentStatus.SUCCESS);t.setProviderPaymentId(payment);payments.save(t);if(t.getType()==PaymentType.PREMIUM)activatePremium(t.getUser());else if(t.getReferenceId()!=null)activateBoost(t);}else if("payment.failed".equals(event)){t.setStatus(PaymentStatus.FAILED);t.setFailureReason(r.path("payload").path("payment").path("entity").path("error_description").asText("Payment failed"));payments.save(t);}}catch(Exception ex){if(ex instanceof ResponseStatusException x)throw x;throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid webhook payload");}}
 private void activatePremium(User u){Subscription s=subscriptions.findByUserId(u.getId()).orElseGet(()->Subscription.builder().user(u).build());LocalDateTime now=LocalDateTime.now();LocalDateTime base=isPremium(u)&&s.getEndDate()!=null?s.getEndDate():now;s.setPlan(SubscriptionPlan.PREMIUM);s.setStatus(SubscriptionStatus.ACTIVE);s.setProvider(PaymentProvider.RAZORPAY);s.setStartDate(s.getStartDate()==null?now:s.getStartDate());s.setEndDate(base.plusDays(premiumDays));s.setAutoRenew(false);subscriptions.save(s);audit(u,"SUBSCRIPTION_ACTIVATED","SUBSCRIPTION",s.getId(),"Premium activated after verified payment");}
 private void activateBoost(PaymentTransaction t){TravelPlan p=plans.findById(t.getReferenceId()).orElse(null);if(p==null||!p.getUser().getId().equals(t.getUser().getId())||boosts.findActive(p.getId(),LocalDateTime.now()).isPresent())return;LocalDateTime n=LocalDateTime.now();boosts.save(BoostedTravelPlan.builder().travelPlan(p).user(t.getUser()).multiplier(boostMultiplier).startedAt(n).expiresAt(n.plusHours(boostHours)).createdAt(n).active(true).build());}
 private PaymentTransaction owned(String id,User u){PaymentTransaction t=payments.findByProviderOrderId(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Payment order not found"));if(!t.getUser().getId().equals(u.getId()))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Payment does not belong to you");return t;}
 private SubscriptionResponse subscriptionResponse(Subscription s){return SubscriptionResponse.builder().plan(s.getPlan().name()).status(s.getStatus().name()).premium(s.getPlan()==SubscriptionPlan.PREMIUM&&s.getStatus()==SubscriptionStatus.ACTIVE&&s.getEndDate()!=null&&s.getEndDate().isAfter(LocalDateTime.now())).startDate(s.getStartDate()).endDate(s.getEndDate()).autoRenew(Boolean.TRUE.equals(s.getAutoRenew())).build();}
 private BoostResponse toBoost(BoostedTravelPlan b){boolean a=b.getActive()&&b.getExpiresAt().isAfter(LocalDateTime.now());if(!a&&b.getActive()){b.setActive(false);boosts.save(b);}return BoostResponse.builder().travelPlanId(b.getTravelPlan().getId()).active(a).multiplier(b.getMultiplier()).startedAt(b.getStartedAt()).expiresAt(b.getExpiresAt()).build();}
 private String photo(User u){return u.getProfilePhoto()==null||u.getProfilePhoto().length==0||u.getProfilePhotoContentType()==null?null:"data:"+u.getProfilePhotoContentType()+";base64,"+Base64.getEncoder().encodeToString(u.getProfilePhoto());}
 private User requireAdmin(){User u=me();if(u.getRole()!=Role.ADMIN)throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Admin access required");return u;} private void audit(User u,String a,String tt,Long id,String d){audits.save(AuditLog.builder().admin(u).action(a).targetType(tt).targetId(id).description(d).createdAt(LocalDateTime.now()).build());} private ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}
}
